const static char nexboot_index_html[] = "<!DOCTYPE html>"
      "<html>\n"
      "<head>\n"
      "  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n"
      "  <style type=\"text/css\">\n"
      "    html, body, iframe { margin: 0; padding: 0; height: 100%; }\n"
      "    iframe { display: block; width: 100%; border: none; }\n"
      "  </style>\n"
      "<title>Nexboot Network Bootloader for ESP32</title>\n"
      "</head>\n"
      "<body>\n"
      "<h1>Nexboot Network Bootloader for ESP32</h1>\n"
      "<div>Select binary firmware to upload</div>\n"
	   "<form name=\"fw_upload\" action=\"/\" method=\"POST\">\n"
		"<input type=\"file\" name=\"fw\">\n"
      "<input type=\"submit\" value=\"upload\">\n"
		"</form>\n"
      "</body>\n"
      "</html>\n";

